---
- name: Generate commands
  hosts: localhost
  tasks:
  - command: python scripts/topology.py hosts

- name: Load commands
  hosts: nodes
  gather_facts: false
  tasks:
  - include_vars:
      file: artifacts/commands.yml

- name: spin up servers
  hosts: nodes
  gather_facts: false
  roles:
    - role: node

- name: assume everyone is a proposer
  hosts: nodes
  roles:
    - role: proposer
